import { Schedule } from '../domain/schedule';

// courseId hace referencia al id auto-incremental de Course (1 = Angular Fundamentals, 2 = TypeScript Advanced Patterns, etc.)
export const MOCK_SCHEDULES: Schedule[] = [
  new Schedule({
    courseId: 1,
    title: 'Angular Fundamentals - Nocturno',
    summary: 'Curso completo de Angular en horario nocturno.',
    chapters: ['Capítulo 1: Introducción', 'Capítulo 2: Componentes', 'Capítulo 3: Servicios'],
    requirements: ['Laptop', 'Conocimientos básicos de HTML y JS'],
    goals: ['Dominar Angular', 'Crear aplicaciones SPA'],
    teacher: 'Profesor García',
    pricePen: 350,
    duration: '3 meses',
    frequency: 'Lunes y Miércoles 7:00pm - 9:00pm',
    dateStart: new Date('2026-05-01'),
  }),
  new Schedule({
    courseId: 1,
    title: 'Angular Fundamentals - Fin de semana',
    summary: 'Curso intensivo de Angular los sábados.',
    chapters: ['Capítulo 1: Introducción', 'Capítulo 2: Componentes', 'Capítulo 3: Servicios'],
    requirements: ['Laptop', 'Conocimientos básicos de HTML y JS'],
    goals: ['Dominar Angular', 'Crear aplicaciones SPA'],
    teacher: 'Profesor López',
    pricePen: 400,
    duration: '2 meses',
    frequency: 'Sábados 9:00am - 1:00pm',
    dateStart: new Date('2026-06-01'),
  }),
  new Schedule({
    courseId: 2,
    title: 'TypeScript Advanced - Nocturno',
    summary: 'Patrones avanzados de TypeScript para desarrollo enterprise.',
    chapters: ['Capítulo 1: Generics', 'Capítulo 2: Decorators', 'Capítulo 3: Utility Types'],
    requirements: ['Conocimientos intermedios de TypeScript'],
    goals: ['Dominar tipos avanzados', 'Aplicar patrones de diseño con TS'],
    teacher: 'Profesor Martínez',
    pricePen: 280,
    duration: '2 meses',
    frequency: 'Martes y Jueves 7:00pm - 9:00pm',
    dateStart: new Date('2026-05-15'),
  }),
  new Schedule({
    courseId: 3,
    title: 'Node.js Backend - Intensivo',
    summary: 'Desarrollo backend con Node.js y Express.',
    chapters: ['Capítulo 1: Fundamentos', 'Capítulo 2: Express', 'Capítulo 3: APIs REST'],
    requirements: ['Laptop', 'Conocimientos de JavaScript'],
    goals: ['Crear APIs REST', 'Manejo de bases de datos'],
    teacher: 'Profesor Rodríguez',
    pricePen: 320,
    duration: '3 meses',
    frequency: 'Lunes a Viernes 6:00pm - 8:00pm',
    dateStart: new Date('2026-07-01'),
  }),
];
