version: "0.2"
phases:
  install:
    runtime-versions:
      nodejs: 24
  pre_build:
    commands:
      - echo "Installing dependencies"
      - cd courses
      - npm ci
  build:
    commands:
      - echo "Starting compilation"
      - npm run build -- --project backoffice --configuration=production
  post_build:
    commands:
      - aws s3 rm s3://course-angular24 --recursive
      - aws s3 sync dist/backoffice/browser s3://course-angular24 --delete
      - aws cloudfront create-invalidation --distribution-id E3GIRMWGPQU6QW --path "/*"
artifacts:
  name: "curso24"
  files:
    - "**/*"
  base-directory: courses/dist/backoffice/browser
